//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Master
    {
        public int CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
    }
}
