//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Master()
        {
            this.OrderItems_Master = new HashSet<OrderItems_Master>();
        }
    
        public int OrderID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string PaymentMethod { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public string ShippingAddress { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string Zipcode { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual City_Master City_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems_Master> OrderItems_Master { get; set; }
        public virtual States_Master States_Master { get; set; }
    }
}
