//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems_Master
    {
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string UserID { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
        public virtual Order_Master Order_Master { get; set; }
    }
}
